### ISSUE TITLE
can we use FullyConsistent in memdb without performance penalty?

### ISSUE THREAD

**Issue by chezgi** [authzed/examples#16]
in the `as-library` example, using `AtLeastAsFresh`.
it seems that in this scenario we can use `FullyConsistent` mode without performance penalty.
or we can use `MinimizeLatency` without any inconsistencies.
is there anything  must be considered here?

**Comment by vroldanbet** [comment]
@chezgi the memory datastore is not meant for high throughput workloads, it was just a reference implementation for testing and we are aware it has some bottlenecks, particularly with writes.

With that said, you can probably use `FullyConsistent` and not get much of the overhead other datastores get because loading relationships is fairly cheap. `MinimizeLatenzy` will behave like other datastores, and so a default staleness of 5.5 seconds is possible
